var data = {
    "height": 1136,
    "pages": [
        {
            "height": 1136,
            "pages": [],
            "id_": "Page2",
            "width": 640,
            "class": "MetProjectPage",
            "nodes": [],
            "name": "Page2"
        }
    ],
    "id_": "Page1",
    "width": 640,
    "class": "MetProjectPage",
    "nodes": [
        {
            "rotation": 0,
            "gradientFill": {
                "gradientAngle": 0,
                "gradientType": 0,
                "endPoint": "{0, 0}",
                "fillAlpha": 1,
                "class": "MetNodeGradientFill",
                "startPoint": "{0, 0}",
                "gradientPoints": []
            },
            "actions": [],
            "class": "MetStateNode",
            "interval": 0,
            "loops": 0,
            "skewY": 0,
            "positionX": 371.5,
            "opacity": 1,
            "duration": 0,
            "sizeY": 312.05,
            "fillType": 0,
            "positionY": 333.475,
            "fillPanelOpen": 1,
            "name": "state1",
            "imageFill": {
                "handlerName": 0,
                "imageRect": "{{0, 0}, {0, 0}}",
                "contentMode": 0,
                "presentationHandlerName": 0,
                "zoom": 1,
                "class": "MetNodeImageFill",
                "sourceRect": "{{0, 0}, {0, 0}}"
            },
            "id_": "state1",
            "nodes": [
                {
                    "color": 0,
                    "fillType": 0,
                    "rotation": 0,
                    "nodeStroke": {
                        "effectEnable": 0,
                        "strokeAlpha": 1,
                        "panelOpen": 0,
                        "strokeWidth": 0,
                        "strokeColor": -1869573889,
                        "strokeLineType": 0,
                        "strokeType": 0,
                        "class": "MetNodeStroke"
                    },
                    "nodeShadow": {
                        "shadowAlpha": 0.5,
                        "effectEnable": 0,
                        "shadowWidth": 4,
                        "shadowColor": 255,
                        "panelOpen": 0,
                        "shadowExpand": 0,
                        "class": "MetNodeShadow",
                        "shadowOffsetX": 1,
                        "shadowOffsetY": 1
                    },
                    "class": "MetStateKeyframeNode",
                    "imageFill": {
                        "handlerName": 0,
                        "imageRect": "{{0, 0}, {0, 0}}",
                        "contentMode": 0,
                        "presentationHandlerName": 0,
                        "zoom": 1,
                        "class": "MetNodeImageFill",
                        "sourceRect": "{{0, 0}, {0, 0}}"
                    },
                    "positionX": 726,
                    "fillPanelOpen": 1,
                    "skewY": 0,
                    "effects": [],
                    "scaleY": 1,
                    "name": "MetStateKeyframeNode1",
                    "anchorX": 0.5,
                    "skewX": 0,
                    "sizeY": 220.05,
                    "anchorY": 0.5,
                    "nodes": [],
                    "opacity": 1,
                    "hooks": [],
                    "id_": "MetStateKeyframeNode1",
                    "positionY": 202.025,
                    "sizeX": 430,
                    "scaleX": 1,
                    "colorFill": {
                        "fillColor": -320017153,
                        "class": "MetNodeColorFill"
                    },
                    "visible": 1,
                    "baseOn": 0,
                    "fillEnable": 1,
                    "gradientFill": {
                        "gradientAngle": 0,
                        "gradientType": 0,
                        "endPoint": "{0, 0}",
                        "fillAlpha": 1,
                        "class": "MetNodeGradientFill",
                        "startPoint": "{0, 0}",
                        "gradientPoints": []
                    },
                    "actions": []
                },
                {
                    "color": 0,
                    "fillType": 0,
                    "rotation": 0,
                    "nodeStroke": {
                        "effectEnable": 0,
                        "strokeAlpha": 1,
                        "panelOpen": 0,
                        "strokeWidth": 0,
                        "strokeColor": -1869573889,
                        "strokeLineType": 0,
                        "strokeType": 0,
                        "class": "MetNodeStroke"
                    },
                    "nodeShadow": {
                        "shadowAlpha": 0.5,
                        "effectEnable": 0,
                        "shadowWidth": 4,
                        "shadowColor": 255,
                        "panelOpen": 0,
                        "shadowExpand": 0,
                        "class": "MetNodeShadow",
                        "shadowOffsetX": 1,
                        "shadowOffsetY": 1
                    },
                    "class": "MetStateKeyframeNode",
                    "imageFill": {
                        "handlerName": 0,
                        "imageRect": "{{0, 0}, {0, 0}}",
                        "contentMode": 0,
                        "presentationHandlerName": 0,
                        "zoom": 1,
                        "class": "MetNodeImageFill",
                        "sourceRect": "{{0, 0}, {0, 0}}"
                    },
                    "positionX": 215,
                    "fillPanelOpen": 1,
                    "skewY": 0,
                    "effects": [],
                    "scaleY": 1,
                    "name": "MetStateKeyframeNode1",
                    "anchorX": 0.5,
                    "skewX": 0,
                    "sizeY": 220.05,
                    "anchorY": 0.5,
                    "nodes": [],
                    "opacity": 1,
                    "hooks": [],
                    "id_": "MetStateKeyframeNode1",
                    "positionY": 110.025,
                    "sizeX": 430,
                    "scaleX": 1,
                    "colorFill": {
                        "fillColor": -320017153,
                        "class": "MetNodeColorFill"
                    },
                    "visible": 1,
                    "baseOn": 0,
                    "fillEnable": 1,
                    "gradientFill": {
                        "gradientAngle": 0,
                        "gradientType": 0,
                        "endPoint": "{0, 0}",
                        "fillAlpha": 1,
                        "class": "MetNodeGradientFill",
                        "startPoint": "{0, 0}",
                        "gradientPoints": []
                    },
                    "actions": []
                }
            ],
            "color": 0,
            "anchorY": 0.5,
            "baseOn": 0,
            "effects": [],
            "defaultState": 0,
            "skewX": 0,
            "visible": 1,
            "nodeShadow": {
                "shadowAlpha": 0.5,
                "effectEnable": 0,
                "shadowWidth": 4,
                "shadowColor": 255,
                "panelOpen": 0,
                "shadowExpand": 0,
                "class": "MetNodeShadow",
                "shadowOffsetX": 1,
                "shadowOffsetY": 1
            },
            "hooks": [],
            "scaleY": 1,
            "fillEnable": 1,
            "colorFill": {
                "fillColor": -320017153,
                "class": "MetNodeColorFill"
            },
            "autoPlay": 0,
            "delay": 0,
            "anchorX": 0.5,
            "scaleX": 1,
            "animation": {
                "autoplay": 0,
                "delay": 0,
                "duration": 2,
                "autoreverses": 0,
                "repeatCount": 0,
                "keyframes": [
                    {
                        "rotation": 0,
                        "rotationY": 0,
                        "time": 0,
                        "controlAX": 0,
                        "class": "MetNodeAnimKeyframe",
                        "positionX": 470.5,
                        "controlBY": 0,
                        "skewY": 0,
                        "scaleY": 1,
                        "anchorX": 0.5,
                        "skewX": 0,
                        "sizeY": 312.05,
                        "anchorY": 0.5,
                        "rotationX": 0,
                        "controlAY": 0,
                        "opacity": 1,
                        "hooks": [],
                        "positionY": 156.025,
                        "controlBX": 0,
                        "sizeX": 941,
                        "scaleX": 1,
                        "visible": 1,
                        "actions": [],
                        "easing": 1
                    },
                    {
                        "rotation": 0.5235988,
                        "rotationY": 0,
                        "time": 2,
                        "controlAX": 0,
                        "class": "MetNodeAnimKeyframe",
                        "positionX": 570.5,
                        "controlBY": 0,
                        "skewY": 0,
                        "scaleY": 1,
                        "anchorX": 0.5,
                        "skewX": 0,
                        "sizeY": 312.05,
                        "anchorY": 0.5,
                        "rotationX": 0,
                        "controlAY": 0,
                        "opacity": 1,
                        "hooks": [],
                        "positionY": 156.025,
                        "controlBX": 0,
                        "sizeX": 941,
                        "scaleX": 1,
                        "visible": 1,
                        "actions": [],
                        "easing": 1
                    }
                ],
                "class": "MetNodeAnim"
            },
            "currentState": 0,
            "sizeX": 941,
            "transition": 0,
            "nodeStroke": {
                "effectEnable": 0,
                "strokeAlpha": 1,
                "panelOpen": 0,
                "strokeWidth": 0,
                "strokeColor": -1869573889,
                "strokeLineType": 0,
                "strokeType": 0,
                "class": "MetNodeStroke"
            }
        },
        {
            "rotation": 0,
            "gradientFill": {
                "gradientAngle": 0,
                "gradientType": 0,
                "endPoint": "{0, 0}",
                "fillAlpha": 1,
                "class": "MetNodeGradientFill",
                "startPoint": "{0, 0}",
                "gradientPoints": []
            },
            "actions": [],
            "radiusY": 16,
            "class": "ShapeNode",
            "skewY": 0,
            "positionX": 414.5,
            "opacity": 1,
            "jpath": [
                "M 0.000000 0.000000",
                "L 467.000000 0.000000",
                "L 467.000000 264.000000",
                "L 0.000000 264.000000",
                "X",
                "M 0.000000 0.000000"
            ],
            "radiusX": 16,
            "sizeY": 264,
            "fillType": 2,
            "positionY": 361.5,
            "fillPanelOpen": 1,
            "name": "rect1",
            "shapeStyle": 1,
            "imageFill": {
                "handlerName": 0,
                "imageRect": "{{0, 0}, {0, 0}}",
                "contentMode": 0,
                "presentationHandlerName": 0,
                "zoom": 1,
                "class": "MetNodeImageFill",
                "sourceRect": "{{0, 0}, {0, 0}}"
            },
            "id_": "rect1",
            "nodes": [],
            "color": 0,
            "anchorY": 0.5,
            "baseOn": 0,
            "effects": [],
            "skewX": 0,
            "visible": 1,
            "nodeShadow": {
                "shadowAlpha": 0.5,
                "effectEnable": 0,
                "shadowWidth": 4,
                "shadowColor": 255,
                "panelOpen": 0,
                "shadowExpand": 0,
                "class": "MetNodeShadow",
                "shadowOffsetX": 1,
                "shadowOffsetY": 1
            },
            "hooks": [],
            "scaleY": 1,
            "fillEnable": 1,
            "colorFill": {
                "fillColor": -320017153,
                "class": "MetNodeColorFill"
            },
            "anchorX": 0.5,
            "scaleX": 1,
            "sizeX": 467,
            "nodeStroke": {
                "effectEnable": 0,
                "strokeAlpha": 1,
                "panelOpen": 0,
                "strokeWidth": 0,
                "strokeColor": -1869573889,
                "strokeLineType": 0,
                "strokeType": 0,
                "class": "MetNodeStroke"
            }
        },
        {
            "color": 0,
            "fillType": 0,
            "rotation": 0,
            "nodeStroke": {
                "effectEnable": 0,
                "strokeAlpha": 1,
                "panelOpen": 0,
                "strokeWidth": 0,
                "strokeColor": -1869573889,
                "strokeLineType": 0,
                "strokeType": 0,
                "class": "MetNodeStroke"
            },
            "nodeShadow": {
                "shadowAlpha": 0.5,
                "effectEnable": 0,
                "shadowWidth": 4,
                "shadowColor": 255,
                "panelOpen": 0,
                "shadowExpand": 0,
                "class": "MetNodeShadow",
                "shadowOffsetX": 1,
                "shadowOffsetY": 1
            },
            "class": "MetNode",
            "imageFill": {
                "handlerName": 0,
                "imageRect": "{{0, 0}, {0, 0}}",
                "contentMode": 0,
                "presentationHandlerName": 0,
                "zoom": 1,
                "class": "MetNodeImageFill",
                "sourceRect": "{{0, 0}, {0, 0}}"
            },
            "positionX": -14.73544,
            "fillPanelOpen": 1,
            "skewY": 0,
            "effects": [],
            "scaleY": 1,
            "name": "group1",
            "anchorX": 0.5,
            "skewX": 0,
            "sizeY": 196,
            "anchorY": 0.5,
            "nodes": [
                {
                    "rotation": 0,
                    "gradientFill": {
                        "gradientAngle": 0,
                        "gradientType": 0,
                        "endPoint": "{0, 0}",
                        "fillAlpha": 1,
                        "class": "MetNodeGradientFill",
                        "startPoint": "{0, 0}",
                        "gradientPoints": []
                    },
                    "actions": [],
                    "class": "TextNode",
                    "skewY": 0,
                    "positionX": 247.9459,
                    "opacity": 1,
                    "blocks": [],
                    "sizeY": 196,
                    "fillType": 0,
                    "positionY": 98,
                    "fillPanelOpen": 1,
                    "name": "label1",
                    "imageFill": {
                        "handlerName": 0,
                        "imageRect": "{{0, 0}, {0, 0}}",
                        "contentMode": 0,
                        "presentationHandlerName": 0,
                        "zoom": 1,
                        "class": "MetNodeImageFill",
                        "sourceRect": "{{0, 0}, {0, 0}}"
                    },
                    "id_": "label1",
                    "nodes": [],
                    "color": 0,
                    "anchorY": 0.5,
                    "baseOn": 0,
                    "effects": [],
                    "skewX": 0,
                    "visible": 1,
                    "nodeShadow": {
                        "shadowAlpha": 0.5,
                        "effectEnable": 0,
                        "shadowWidth": 4,
                        "shadowColor": 255,
                        "panelOpen": 0,
                        "shadowExpand": 0,
                        "class": "MetNodeShadow",
                        "shadowOffsetX": 1,
                        "shadowOffsetY": 1
                    },
                    "hooks": [],
                    "scaleY": 1,
                    "fillEnable": 1,
                    "colorFill": {
                        "fillColor": -320017153,
                        "class": "MetNodeColorFill"
                    },
                    "anchorX": 0.5,
                    "scaleX": 1,
                    "sizeX": 367.05,
                    "nodeStroke": {
                        "effectEnable": 0,
                        "strokeAlpha": 1,
                        "panelOpen": 0,
                        "strokeWidth": 0,
                        "strokeColor": -1869573889,
                        "strokeLineType": 0,
                        "strokeType": 0,
                        "class": "MetNodeStroke"
                    }
                },
                {
                    "rotation": 0.09431395,
                    "gradientFill": {
                        "gradientAngle": 0,
                        "gradientType": 0,
                        "endPoint": "{0, 0}",
                        "fillAlpha": 1,
                        "class": "MetNodeGradientFill",
                        "startPoint": "{0, 0}",
                        "gradientPoints": []
                    },
                    "actions": [],
                    "class": "MetLineNode",
                    "lineWidth": 0,
                    "skewY": 0,
                    "positionX": 74.47087,
                    "opacity": 1,
                    "lineStartPointY": 50,
                    "lineEndPointY": 64,
                    "sizeY": 10,
                    "fillType": 0,
                    "positionY": 57,
                    "fillPanelOpen": 1,
                    "name": "line1",
                    "imageFill": {
                        "handlerName": 0,
                        "imageRect": "{{0, 0}, {0, 0}}",
                        "contentMode": 0,
                        "presentationHandlerName": 0,
                        "zoom": 1,
                        "class": "MetNodeImageFill",
                        "sourceRect": "{{0, 0}, {0, 0}}"
                    },
                    "id_": "line1",
                    "nodes": [],
                    "color": 0,
                    "anchorY": 0.5,
                    "baseOn": 0,
                    "effects": [],
                    "skewX": 0,
                    "visible": 1,
                    "nodeShadow": {
                        "shadowAlpha": 0.5,
                        "effectEnable": 0,
                        "shadowWidth": 4,
                        "shadowColor": 255,
                        "panelOpen": 0,
                        "shadowExpand": 0,
                        "class": "MetNodeShadow",
                        "shadowOffsetX": 1,
                        "shadowOffsetY": 1
                    },
                    "hooks": [],
                    "scaleY": 1,
                    "fillEnable": 1,
                    "colorFill": {
                        "fillColor": -320017153,
                        "class": "MetNodeColorFill"
                    },
                    "lineStartPointX": 0.4708724,
                    "lineStartStyle": 0,
                    "anchorX": 0.5,
                    "scaleX": 1,
                    "lineEndStyle": 0,
                    "lineEndPointX": 148.4709,
                    "sizeX": 148.6607,
                    "nodeStroke": {
                        "effectEnable": 0,
                        "strokeAlpha": 1,
                        "panelOpen": 0,
                        "strokeWidth": 0,
                        "strokeColor": -1869573889,
                        "strokeLineType": 0,
                        "strokeType": 0,
                        "class": "MetNodeStroke"
                    },
                    "lineStyle": 0
                }
            ],
            "opacity": 1,
            "hooks": [],
            "id_": "group1",
            "positionY": 663.5,
            "sizeX": 431.4709,
            "scaleX": 1,
            "colorFill": {
                "fillColor": -320017153,
                "class": "MetNodeColorFill"
            },
            "visible": 1,
            "baseOn": 0,
            "fillEnable": 1,
            "gradientFill": {
                "gradientAngle": 0,
                "gradientType": 0,
                "endPoint": "{0, 0}",
                "fillAlpha": 1,
                "class": "MetNodeGradientFill",
                "startPoint": "{0, 0}",
                "gradientPoints": []
            },
            "actions": []
        }
    ],
    "name": "Page1"
}